### ISSUE TITLE
Broken dependency in requirements.txt

### ISSUE THREAD

**Issue by abhinavnatarajan** [Cimagroup/vectorization-maps#5]
The version of scikit-learn specified in `requirements.txt` is incompatible with `vectorization/GetNewMethods.py`. The line that causes the incompatibility is https://github.com/Cimagroup/vectorization-maps/blob/67e3b3880867f150a2b601f86b29bd984beeabcb/vectorization/GetNewMethods.py#L10
`sklearn.neighbors` does not contain the class `DistanceMetric` for any version of `scikit-learn` >= 0.24.2. This error breaks some methods in `vectorization/vectorizationmethods.py` as well.

**Comment by Soriano-Trigueros** [comment]
Thanks for the comment!
In the version of sklearn we were using, `sklearn.neighbors.DistanceMetric` works, but a warning appears noticing that it was being moved to `sklearn.metrics.DistanceMetric`.
We have updated the script to load it from `sklearn.metrics`, the problem should be solved now.
